### ISSUE TITLE
Fix the on:hover show resources menu

### ISSUE THREAD

**Issue by bibekshhh** [ZIELN/zieln-frontend#2]
![image](https://github.com/ZIELN/zieln-frontend/assets/90471455/307fab88-e504-419b-b090-2cb0d89bb893)

**Comment by bibekshhh** [comment]
This issue is still persistent on the mobile view of the navbar @bini2002

**Comment by bini2002** [comment]
@bibekshhh 
I am unable to fix this. I think It's issue with the preline.
If you can provide the contents for the resources dropdown, I can create it using Ant Design.

**Comment by bibekshhh** [comment]
> If you can provide the contents for the resources dropdown, I can create it using Ant Design.

@bini2002 
Did you check this? https://preline.co/examples/navigations-mega-menu.html
